title: Calciosplash Lizzana
email: gsp_lizzana@gmail.com
description: >-
  IL MONDIALE SI GIOCA SUL GONFIABILE
baseurl: "/calciosplash_lizzana"
url: "calciosplashlizzana.it" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: gsplizzana
youtube_username: gsplizzana
twitch_username: gsplizzana
twitter_username: gsplizzana

encoding: UTF-8

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-relative-links
